name: auto-sprint-loop
description: "Fully automated sprint loop: create story → validate → fix story → dev → review → fix → repeat until sprint-status is complete (Beads-backed, resumable)."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
date: system-generated
sprint_artifacts: "{config_source}:sprint_artifacts"
sprint_status: "{sprint_artifacts}/sprint-status.yaml || {output_folder}/sprint-status.yaml"

# Beads (Identity Memory) integration
beads:
  enabled: "{config_source}:beads_enabled || true"
  db: "{project-root}/_bmad/_beads/beads.json"
  lock_name: "plane"
  cli:
    init: "bmad beads init --directory {project-root}"
    land: "bmad beads land --directory {project-root}"
    get: "bmad beads get"
    set: "bmad beads set"
    append: "bmad beads append"

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/auto-sprint-loop"
instructions: "{installed_path}/instructions.xml"
validation: false
template: false

# Project context
project_context: "**/project-context.md"

standalone: true
web_bundle: false
